export const PidData = ['iT9r9E7rAsbbh',
'yxvyR50n0zlpi',
'r49mGE4Hwegxh',
'Y8NEFS9igeevL',
'ii9ZfnCghgHVw',
'7LyVZJMQYo856',
'fognJIoHsNllm',
'9u7ELf5TmNjFO',
'9pZEAsd8N5jS4',
'0Q6e38lxEEx8y',
'uoLlc1VBf2AIG',
'WViPImJHfBQsP',
'kdVl6bkURna4u',
'tdOIOeq9vZlf4',
'vCj6LRPbgjCXW',
'YjsEyAQhcQ4hz',
'Vkt1V5NLS8xG0',
'LC8Pmuu9TX30m',
'Q27pkG84HIgdo',
'9SraShJBWNV1l',
'PgPWXYvUNTqgA',
'DJ41Xl7kx74aL',
'YO5BSs5hJO2Vn',
'L4pCo6v0FTfSR',
'XCglSprRSzdKL',
'IhhWNjDd8eMFH',
'Uw9gcnxPCI9DZ',
'QyrsyxOLg1h8j',
'8BExfkq0hmQO1',
'uU1JOUXMBLxey',
'gl0GNY3aTIQAv',
'AfPQTXQz8GJ7k',
'IOd99arvEz41J',
'ks3Pl46KIkFMG',
'M8ESWfTrwsDiq',
'fAek5IuIwY2J8',
'qc9qy2Yttw4S5',
'22zwmxYRcV5V6',
'dDmgIGiU1Uv1S',
'ADfQkUc3QAYQS',
'ZmdXLhMtHq7YT',
'wAcazx0gIcfuP',
'wRc5PA6ZXPDOQ',
'pUPDDtWVNshaU',
'EtP5Z7LGX2BFf',
'JVzs9kK7swlVd',
't0M4Y1Xzrrd01',
'22gPUqrt2SasV',
'4i9ka2f4XrcNK',
'0iXj2U5pnz013',
'lE5fGe95eXcRu',
'BYwG2M6fQK5fU',
'Gy09KbDCVTkAV',
'hr9cSp6WeAndg',
'dEakX4GkTTUqY',
'dwmovkC9bpUv2',
'OLwAW5W8kNaJb',
'6xixIEVeTovAV',
'cdJLo2W1GVPmB',
'G8nWFjQz5FBhd',
'Ayc2P8tDMQ97f',
'BQ6H3sGgchtcX',
'UjJmxZw6cH1KE',
'xDTGFIuRAOftw',
'yznAFnTbu6Jvz',
'Mh6XS525kbNnb',
'hY62HFP3mV7TR',
'ZukvY5oC7hzf6',
'SF2tH249oTfep',
'DzzQpmzpoZp3G',
'BpaCdNYnKY3WT',
'qEyPivIXR2z2X',
'8BpqlfY4PTvY5',
'n7G4vvywclovD',
'bgrsTaRawXjak',
'zFwrYR0Hz86rM',
'dxNSa50vFDb5q',
'Z5OUdLQjLulkk',
'IzZVH0sI0RI2g',
'CNxsJnJJAPbRa',
'DbAGgc5h1U9YN',
'FT6AtM9QZosHX',
'WKlSe48uAtKHQ',
'C7Wizh5Yl4e6S',
'JyFbCou097Zrs',
'Lh2QlxebsK74S',
'9S9FODLW6PSFP',
'Q9g3LSbuHWbx2',
'HN1gOaN0qyYpG',
'b5fbbw3InSSgW',
'dElEtEpRoBlEm',
'vGFOe9rpKzr5S',
'3xtmM9Z38HVlm',
'qiL9AYsXhqpMJ',
'VLDA3omogrKUn',
'eAfydRGlBCK1f',
'5FufiWmJwJeZb',
'TaeaVXtOw3rNH',
'SXvckTdvawqhp',
'I4kqd6vEhBSnV']
export const ProblemData = [{
    answer: 'FALL',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '1',
    location: "예지관",
    difficulty: "VE",
    },
    {
    answer: '260',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '2',
    location: "대자연",
    difficulty: "VH",
    },
    {
    answer: '시장',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '3',
    location: "우암관",
    difficulty: "N",
    },
    {
    answer: '56000',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '4',
    location: "우암관",
    difficulty: "H",
    },
    {
    answer: '창동',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '5',
    location: "인재관",
    difficulty: "E",
    },
    {
    answer: '포켓몬스터',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '6',
    location: "인재관",
    difficulty: "N",
    },
    {
    answer: 'VariationsonawaltzbyDiabelli',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '7',
    location: "우암관",
    difficulty: "E",
    },
    {
    answer: '12',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '8',
    location: "예지관",
    difficulty: "E",
    },
    {
    answer: '925',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '9',
    location: "예지관",
    difficulty: "E",
    },
    {
    answer: '21304',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '10',
    location: "예지관",
    difficulty: "H",
    },
    {
    answer: '롯데리아',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '11',
    location: "예지관",
    difficulty: "N",
    },
    {
    answer: '宮',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '12',
    location: "대자연",
    difficulty: "VH",
    },
    {
    answer: '광주원주고속도로',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '13',
    location: "대자연",
    difficulty: "N",
    },
    {
    answer: '51',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '14',
    location: "대자연",
    difficulty: "E",
    },
    {
    answer: '에델바이스',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '15',
    location: "우암관",
    difficulty: "VH",
    },
    {
    answer: '꽁',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '16',
    location: "인재관",
    difficulty: "VE",
    },
    {
    answer: 'IATA',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '17',
    location: "예지관",
    difficulty: "E",
    },
    {
    answer: '음',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '18',
    location: "인재관",
    difficulty: "N",
    },
    {
    answer: 'Black',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '19',
    location: "인재관",
    difficulty: "E",
    },
    {
    answer: 'THREE',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '20',
    location: "대자연",
    difficulty: "H",
    },
    {
    answer: 'ㄷ$ㄷ^',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '21',
    location: "대자연",
    difficulty: "N",
    },
    {
    answer: '나이트',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '22',
    location: "대자연",
    difficulty: "E",
    },
    {
    answer: '대황',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '23',
    location: "대자연",
    difficulty: "VE",
    },
    {
    answer: 'huckel',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '24',
    location: "인재관",
    difficulty: "E",
    },
    {
    answer: '8',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '25',
    location: "우암관",
    difficulty: "N",
    },
    {
    answer: '간체자',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '26',
    location: "우암관",
    difficulty: "VH",
    },
    {
    answer: '6',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '27',
    location: "예지관",
    difficulty: "E",
    },
    {
    answer: '丑',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '28',
    location: "우암관",
    difficulty: "E",
    },
    {
    answer: '아데닌',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '29',
    location: "우암관",
    difficulty: "N",
    },
    {
    answer: 'TimesSquare',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '30',
    location: "대자연",
    difficulty: "H",
    },
    {
    answer: '코소보',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '31',
    location: "우암관",
    difficulty: "H",
    },
    {
    answer: '229680',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '32',
    location: "예지관",
    difficulty: "E",
    },
    {
    answer: '꽃',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '33',
    location: "예지관",
    difficulty: "H",
    },
    {
    answer: '3408',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '34',
    location: "우암관",
    difficulty: "E",
    },
    {
    answer: 'Promise',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '35',
    location: "인재관",
    difficulty: "E",
    },
    {
    answer: '이승만',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '36',
    location: "우암관",
    difficulty: "VE",
    },
    {
    answer: '82',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '37',
    location: "예지관",
    difficulty: "E",
    },
    {
    answer: '광복절',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '38',
    location: "예지관",
    difficulty: "N",
    },
    {
    answer: 'UP',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '39',
    location: "인재관",
    difficulty: "N",
    },
    {
    answer: 'January',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '40',
    location: "인재관",
    difficulty: "E",
    },
    {
    answer: 'Eunoia',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '41',
    location: "인재관",
    difficulty: "N",
    },
    {
    answer: '가장넓은길',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '42',
    location: "인재관",
    difficulty: "N",
    },
    {
    answer: '51',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '43',
    location: "대자연",
    difficulty: "H",
    },
    {
    answer: 'I116',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '44',
    location: "대자연",
    difficulty: "N",
    },
    {
    answer: '41',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '45',
    location: "대자연",
    difficulty: "?",
    },
    {
    answer: '베텔게우스',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '46',
    location: "우암관",
    difficulty: "N",
    },
    {
    answer: '수학',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '47',
    location: "우암관",
    difficulty: "VE",
    },
    {
    answer: 'DRIVE',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '48',
    location: "예지관",
    difficulty: "VE",
    },
    {
    answer: '하이바라',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '49',
    location: "우암관",
    difficulty: "VE",
    },
    {
    answer: '참치',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '50',
    location: "우암관",
    difficulty: "E",
    },
    {
    answer: '19480815',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '51',
    location: "예지관",
    difficulty: "N",
    },
    {
    answer: '998',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '52',
    location: "우암관",
    difficulty: "N",
    },
    {
    answer: '국제시장',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '53',
    location: "예지관",
    difficulty: "H",
    },
    {
    answer: '3205',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '54',
    location: "대자연",
    difficulty: "N",
    },
    {
    answer: 'H1ntC0d3',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '55',
    location: "예지관",
    difficulty: "E",
    },
    {
    answer: '물보',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '56',
    location: "예지관",
    difficulty: "N",
    },
    {
    answer: '예술사',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '57',
    location: "인재관",
    difficulty: "N",
    },
    {
    answer: 'lecoqsportif',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '58',
    location: "인재관",
    difficulty: "E",
    },
    {
    answer: '금식은물도금한다',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '59',
    location: "대자연",
    difficulty: "E",
    },
    {
    answer: '39',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '60',
    location: "예지관",
    difficulty: "E",
    },
    {
    answer: 'SwimSwim',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '61',
    location: "대자연",
    difficulty: "N",
    },
    {
    answer: '오렌지',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '62',
    location: "인재관",
    difficulty: "VE",
    },
    {
    answer: '150',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '63',
    location: "인재관",
    difficulty: "E",
    },
    {
    answer: '아이템',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '64',
    location: "대자연",
    difficulty: "VE",
    },
    {
    answer: '5',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '65',
    location: "대자연",
    difficulty: "VE",
    },
    {
    answer: '순신',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '66',
    location: "우암관",
    difficulty: "N",
    },
    {
    answer: '2529',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '67',
    location: "예지관",
    difficulty: "H",
    },
    {
    answer: '%茶비타여명',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '68',
    location: "인재관",
    difficulty: "E",
    },
    {
    answer: '111',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '69',
    location: "우암관",
    difficulty: "E",
    },
    {
    answer: 'SPADE',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '70',
    location: "대자연",
    difficulty: "N",
    },
    {
    answer: 'reopen',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '71',
    location: "인재관",
    difficulty: "VE",
    },
    {
    answer: '버드나무',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '72',
    location: "대자연",
    difficulty: "VE",
    },
    {
    answer: 'coral',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '73',
    location: "인재관",
    difficulty: "E",
    },
    {
    answer: 'television',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '74',
    location: "인재관",
    difficulty: "N",
    },
    {
    answer: '바지락',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '75',
    location: "인재관",
    difficulty: "VE",
    },
    {
    answer: '25355253',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '76',
    location: "예지관",
    difficulty: "N",
    },
    {
    answer: '약학대학',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '77',
    location: "인재관",
    difficulty: "VE",
    },
    {
    answer: '6720',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '78',
    location: "대자연",
    difficulty: "H",
    },
    {
    answer: 'LILAC',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '79',
    location: "예지관",
    difficulty: "N",
    },
    {
    answer: 'TheValleyofFear',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '80',
    location: "우암관",
    difficulty: "?",
    },
    {
    answer: 'Adequate',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '4.3',
    location: "인재관",
    difficulty: "VE",
    },
    {
    answer: '1488565',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '1.01',
    location: "예지관",
    difficulty: "N",
    },
    {
    answer: 'DEDI',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '1/10',
    location: "예지관",
    difficulty: "E",
    },
    {
    answer: 'WhoWhenWhereWhatHowWhy',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '6.1',
    location: "우암관",
    difficulty: "E",
    },
    {
    answer: '50',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '9.6',
    location: "인재관",
    difficulty: "N",
    },
    {
    answer: 'sshs1sshs!',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: 'null',
    location: "인재관",
    difficulty: "E",
    },
    {
    answer: 'I',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: 'e',
    location: "우암관",
    difficulty: "E",
    },
    {
    answer: '8.504',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: 'π',
    location: "우암관",
    difficulty: "N",
    },
    {
    answer: '77760',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '4π',
    location: "예지관",
    difficulty: "E",
    },
    {
    answer: '59%',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '0',
    location: "예지관",
    difficulty: "N",
    },
    {
    answer: 'ERROR',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: 'ReferenceERROR',
    location: "예지관",
    difficulty: "?",
    },
    {
    answer: '꽃밥',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '10.3683',
    location: "우암관",
    difficulty: "E",
    },
    {
    answer: '아타고',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '34.37',
    location: "대자연",
    difficulty: "H",
    },
    {
    answer: '알데바란',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '1.2',
    location: "우암관",
    difficulty: "N",
    },
    {
    answer: '의행관',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '2/3',
    location: "대자연",
    difficulty: "N",
    },
    {
    answer: '공인회계사',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '3.91',
    location: "인재관",
    difficulty: "VE",
    },
    {
    answer: '13',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '12.1',
    location: "우암관",
    difficulty: "H",
    },
    {
    answer: '시작',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '√2020',
    location: "대자연",
    difficulty: "N",
    },
    {
    answer: '런던',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '37.127',
    location: "대자연",
    difficulty: "N",
    },
    {
    answer: '제임스웹망원경',
    count: 0,
    find: 0,
    foundList: [],
    solvedList: [],
    no: '12.25',
    location: "대자연",
    difficulty: "E",
    }]

export const noTocode = new Map([["1", "iT9r9E7rAsbbh"],
["2", "yxvyR50n0zlpi"],
["3", "r49mGE4Hwegxh"],
["4", "Y8NEFS9igeevL"],
["5", "ii9ZfnCghgHVw"],
["6", "7LyVZJMQYo856"],
["7", "fognJIoHsNllm"],
["8", "9u7ELf5TmNjFO"],
["9", "9pZEAsd8N5jS4"],
["10", "0Q6e38lxEEx8y"],
["11", "uoLlc1VBf2AIG"],
["12", "WViPImJHfBQsP"],
["13", "kdVl6bkURna4u"],
["14", "tdOIOeq9vZlf4"],
["15", "vCj6LRPbgjCXW"],
["16", "YjsEyAQhcQ4hz"],
["17", "Vkt1V5NLS8xG0"],
["18", "LC8Pmuu9TX30m"],
["19", "Q27pkG84HIgdo"],
["20", "9SraShJBWNV1l"],
["21", "PgPWXYvUNTqgA"],
["22", "DJ41Xl7kx74aL"],
["23", "YO5BSs5hJO2Vn"],
["24", "L4pCo6v0FTfSR"],
["25", "XCglSprRSzdKL"],
["26", "IhhWNjDd8eMFH"],
["27", "Uw9gcnxPCI9DZ"],
["28", "QyrsyxOLg1h8j"],
["29", "8BExfkq0hmQO1"],
["30", "uU1JOUXMBLxey"],
["31", "gl0GNY3aTIQAv"],
["32", "AfPQTXQz8GJ7k"],
["33", "IOd99arvEz41J"],
["34", "ks3Pl46KIkFMG"],
["35", "M8ESWfTrwsDiq"],
["36", "fAek5IuIwY2J8"],
["37", "qc9qy2Yttw4S5"],
["38", "22zwmxYRcV5V6"],
["39", "dDmgIGiU1Uv1S"],
["40", "ADfQkUc3QAYQS"],
["41", "ZmdXLhMtHq7YT"],
["42", "wAcazx0gIcfuP"],
["43", "wRc5PA6ZXPDOQ"],
["44", "pUPDDtWVNshaU"],
["45", "EtP5Z7LGX2BFf"],
["46", "JVzs9kK7swlVd"],
["47", "t0M4Y1Xzrrd01"],
["48", "22gPUqrt2SasV"],
["49", "4i9ka2f4XrcNK"],
["50", "0iXj2U5pnz013"],
["51", "lE5fGe95eXcRu"],
["52", "BYwG2M6fQK5fU"],
["53", "Gy09KbDCVTkAV"],
["54", "hr9cSp6WeAndg"],
["55", "dEakX4GkTTUqY"],
["56", "dwmovkC9bpUv2"],
["57", "OLwAW5W8kNaJb"],
["58", "6xixIEVeTovAV"],
["59", "cdJLo2W1GVPmB"],
["60", "G8nWFjQz5FBhd"],
["61", "Ayc2P8tDMQ97f"],
["62", "BQ6H3sGgchtcX"],
["63", "UjJmxZw6cH1KE"],
["64", "xDTGFIuRAOftw"],
["65", "yznAFnTbu6Jvz"],
["66", "Mh6XS525kbNnb"],
["67", "hY62HFP3mV7TR"],
["68", "ZukvY5oC7hzf6"],
["69", "SF2tH249oTfep"],
["70", "DzzQpmzpoZp3G"],
["71", "BpaCdNYnKY3WT"],
["72", "qEyPivIXR2z2X"],
["73", "8BpqlfY4PTvY5"],
["74", "n7G4vvywclovD"],
["75", "bgrsTaRawXjak"],
["76", "zFwrYR0Hz86rM"],
["77", "dxNSa50vFDb5q"],
["78", "Z5OUdLQjLulkk"],
["79", "IzZVH0sI0RI2g"],
["80", "CNxsJnJJAPbRa"],
["4.3", "DbAGgc5h1U9YN"],
["1.01", "FT6AtM9QZosHX"],
["1/10", "WKlSe48uAtKHQ"],
["6.1", "C7Wizh5Yl4e6S"],
["9.6", "JyFbCou097Zrs"],
["null", "Lh2QlxebsK74S"],
["e", "9S9FODLW6PSFP"],
["π", "Q9g3LSbuHWbx2"],
["4π", "HN1gOaN0qyYpG"],
["0", "b5fbbw3InSSgW"],
["ReferenceERROR", "dElEtEpRoBlEm"],
["10.3683", "vGFOe9rpKzr5S"],
["34.37", "3xtmM9Z38HVlm"],
["1.2", "qiL9AYsXhqpMJ"],
["2/3", "VLDA3omogrKUn"],
["3.91", "eAfydRGlBCK1f"],
["12.1", "5FufiWmJwJeZb"],
["√2020", "TaeaVXtOw3rNH"],
["37.127", "SXvckTdvawqhp"],
["12.25", "I4kqd6vEhBSnV"]])

export const codeTono = new Map([["iT9r9E7rAsbbh", "1"],
["yxvyR50n0zlpi", "2"],
["r49mGE4Hwegxh", "3"],
["Y8NEFS9igeevL", "4"],
["ii9ZfnCghgHVw", "5"],
["7LyVZJMQYo856", "6"],
["fognJIoHsNllm", "7"],
["9u7ELf5TmNjFO", "8"],
["9pZEAsd8N5jS4", "9"],
["0Q6e38lxEEx8y", "10"],
["uoLlc1VBf2AIG", "11"],
["WViPImJHfBQsP", "12"],
["kdVl6bkURna4u", "13"],
["tdOIOeq9vZlf4", "14"],
["vCj6LRPbgjCXW", "15"],
["YjsEyAQhcQ4hz", "16"],
["Vkt1V5NLS8xG0", "17"],
["LC8Pmuu9TX30m", "18"],
["Q27pkG84HIgdo", "19"],
["9SraShJBWNV1l", "20"],
["PgPWXYvUNTqgA", "21"],
["DJ41Xl7kx74aL", "22"],
["YO5BSs5hJO2Vn", "23"],
["L4pCo6v0FTfSR", "24"],
["XCglSprRSzdKL", "25"],
["IhhWNjDd8eMFH", "26"],
["Uw9gcnxPCI9DZ", "27"],
["QyrsyxOLg1h8j", "28"],
["8BExfkq0hmQO1", "29"],
["uU1JOUXMBLxey", "30"],
["gl0GNY3aTIQAv", "31"],
["AfPQTXQz8GJ7k", "32"],
["IOd99arvEz41J", "33"],
["ks3Pl46KIkFMG", "34"],
["M8ESWfTrwsDiq", "35"],
["fAek5IuIwY2J8", "36"],
["qc9qy2Yttw4S5", "37"],
["22zwmxYRcV5V6", "38"],
["dDmgIGiU1Uv1S", "39"],
["ADfQkUc3QAYQS", "40"],
["ZmdXLhMtHq7YT", "41"],
["wAcazx0gIcfuP", "42"],
["wRc5PA6ZXPDOQ", "43"],
["pUPDDtWVNshaU", "44"],
["EtP5Z7LGX2BFf", "45"],
["JVzs9kK7swlVd", "46"],
["t0M4Y1Xzrrd01", "47"],
["22gPUqrt2SasV", "48"],
["4i9ka2f4XrcNK", "49"],
["0iXj2U5pnz013", "50"],
["lE5fGe95eXcRu", "51"],
["BYwG2M6fQK5fU", "52"],
["Gy09KbDCVTkAV", "53"],
["hr9cSp6WeAndg", "54"],
["dEakX4GkTTUqY", "55"],
["dwmovkC9bpUv2", "56"],
["OLwAW5W8kNaJb", "57"],
["6xixIEVeTovAV", "58"],
["cdJLo2W1GVPmB", "59"],
["G8nWFjQz5FBhd", "60"],
["Ayc2P8tDMQ97f", "61"],
["BQ6H3sGgchtcX", "62"],
["UjJmxZw6cH1KE", "63"],
["xDTGFIuRAOftw", "64"],
["yznAFnTbu6Jvz", "65"],
["Mh6XS525kbNnb", "66"],
["hY62HFP3mV7TR", "67"],
["ZukvY5oC7hzf6", "68"],
["SF2tH249oTfep", "69"],
["DzzQpmzpoZp3G", "70"],
["BpaCdNYnKY3WT", "71"],
["qEyPivIXR2z2X", "72"],
["8BpqlfY4PTvY5", "73"],
["n7G4vvywclovD", "74"],
["bgrsTaRawXjak", "75"],
["zFwrYR0Hz86rM", "76"],
["dxNSa50vFDb5q", "77"],
["Z5OUdLQjLulkk", "78"],
["IzZVH0sI0RI2g", "79"],
["CNxsJnJJAPbRa", "80"],
["DbAGgc5h1U9YN", "4.3"],
["FT6AtM9QZosHX", "1.01"],
["WKlSe48uAtKHQ", "1/10"],
["C7Wizh5Yl4e6S", "6.1"],
["JyFbCou097Zrs", "9.6"],
["Lh2QlxebsK74S", "null"],
["9S9FODLW6PSFP", "e"],
["Q9g3LSbuHWbx2", "π"],
["HN1gOaN0qyYpG", "4π"],
["b5fbbw3InSSgW", "0"],
["dElEtEpRoBlEm", "ReferenceERROR"],
["vGFOe9rpKzr5S", "10.3683"],
["3xtmM9Z38HVlm", "34.37"],
["qiL9AYsXhqpMJ", "1.2"],
["VLDA3omogrKUn", "2/3"],
["eAfydRGlBCK1f", "3.91"],
["5FufiWmJwJeZb", "12.1"],
["TaeaVXtOw3rNH", "√2020"],
["SXvckTdvawqhp", "37.127"],
["I4kqd6vEhBSnV", "12.25"]])